In [1]:
import pandas as pd
import numpy as np
import statistics

In [2]:
balance_df = pd.read_csv('balance_sheet.csv')

In [3]:
income_df = pd.read_csv('income_sheet.csv')

In [4]:
balance_df

Items  Previous   Current
0      Cash and cash equivalents   1325553    201888
1           Accounts receivables  11539999  14536542
2                Tax receivables    602990    524077
3              Other receivables         0         0
4         Other short-term asset         0         0
5                      Inventory  12910944   7972010
6                Prepaid expense        88      2038
7            Other current asset         0         0
8                            SDS         0         0
9           Total current assets  26379576  23236557
10                           PPE   2834360   3106204
11              Intangible asset      4810      4810
12              Biological asset         0         0
13          Long-term investment         0         0
14                  Deferred tax         0         0
15       Other non-current asset         0         0
16       Total non-current asset   2839171   3111014
17                   Total asset  29218747  26347571
18              Accounts payable  22726905  19622619
19              Salaries payable     75084     57735
20                   Tax payable    124604     71167
21     Social securities payable     40812     18756
22               Short-term debt         0         0
23              Interest payable         0         0
24              Dividend payable   1198755   1154371
25              Unearned revenue         0         0
26  Other short-term liabilities     37165     40096
27     Total current liabilities  24203327  20964745
28                Long-term debt         0         0
29           Deferred income tax         0         0
30   Other long-term liabilities         0         0
31   Total long-term liabilities         0         0
32             Total liabilities  24203327  20964745
33                        Equity    377820    377820
34                  Common stock    377820    377820
35                Diluted stocks   1402398   1402398
36             Retained earnings   3235201   3602607
37           Stockholders equity   5015420   5382825

In [5]:
income_df

Items  Previous   Current
0                             Revenue/sales  49176616  17030458
1                                      COGS  47641973  16827391
2                              Gross profit   1534643    203066
3                               Rent income         0         0
4                           Interest income         0         0
5                           Dividend income         0         0
6                              Other income   2015126   1922904
7                  Sales, marketing expense    190438    101173
8                    General, admin expense    762567    444750
9                           Finance expense         0         0
10                            Other expense   1043460   1171817
11              Currency exchange gain/loss         0         0
12     Sales of long term assets gain/ loss    -18737         0
13  Sales of non-current assets gain / loss         0         0
14                    Investment gain/ loss         0         0
15                                      EBT   1534565    408228
16                               Income tax    165541     40822
17                               Net income   1369024    367405

## Formula

In [6]:
def current_ratio(quarter):
    ca = balance_df.iloc[balance_df[balance_df['Items'] == 'Total current assets'].index, balance_df.columns.get_loc(quarter)].values
    cl = balance_df.iloc[balance_df[balance_df['Items'] == 'Total current liabilities'].index, balance_df.columns.get_loc(quarter)].values
    current = ca / cl
    return current

In [7]:
current_ratio("Current")

array([1.10836345])

In [8]:
def quick_ratio(quarter):
    cash = balance_df.iloc[balance_df[balance_df['Items'] == 'Cash and cash equivalents'].index, balance_df.columns.get_loc(quarter)].values
    sds = balance_df.iloc[balance_df[balance_df['Items'] == 'SDS'].index, balance_df.columns.get_loc(quarter)].values
    ar = balance_df.iloc[balance_df[balance_df['Items'] == 'Accounts receivables'].index, balance_df.columns.get_loc(quarter)].values
    tr = balance_df.iloc[balance_df[balance_df['Items'] == 'Tax receivables'].index, balance_df.columns.get_loc(quarter)].values
    other_r = balance_df.iloc[balance_df[balance_df['Items'] == 'Other receivables'].index, balance_df.columns.get_loc(quarter)].values
    
    cl = balance_df.iloc[balance_df[balance_df['Items'] == 'Total current liabilities'].index, balance_df.columns.get_loc(quarter)].values
    
    quick = (cash + sds + ar + tr + other_r) / cl
    return quick

In [9]:
quick_ratio("Previous")

array([0.55647482])

In [10]:
def cash_ratio(quarter):
    cash = balance_df.iloc[balance_df[balance_df['Items'] == 'Cash and cash equivalents'].index, balance_df.columns.get_loc(quarter)].values
    sds = balance_df.iloc[balance_df[balance_df['Items'] == 'SDS'].index, balance_df.columns.get_loc(quarter)].values
    cl = balance_df.iloc[balance_df[balance_df['Items'] == 'Total current liabilities'].index, balance_df.columns.get_loc(quarter)].values
    
    result = (cash + sds) / cl
    return result

In [11]:
cash_ratio("Previous")

array([0.05476739])

In [12]:
def td_ratio(quarter):
    short_debt = balance_df.iloc[balance_df[balance_df['Items'] == 'Short-term debt'].index, balance_df.columns.get_loc(quarter)].values
    long_debt = balance_df.iloc[balance_df[balance_df['Items'] == 'Long-term debt'].index, balance_df.columns.get_loc(quarter)].values
    
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc(quarter)].values
    
    result = (short_debt + long_debt) / ta
    return result

In [13]:
td_ratio("Previous")

array([0.])

In [14]:
def debt_equity_ratio(quarter):
    short_debt = balance_df.iloc[balance_df[balance_df['Items'] == 'Short-term debt'].index, balance_df.columns.get_loc(quarter)].values
    long_debt = balance_df.iloc[balance_df[balance_df['Items'] == 'Long-term debt'].index, balance_df.columns.get_loc(quarter)].values
    
    te = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc(quarter)].values
    
    result = (short_debt + long_debt) / te
    return result
    

In [15]:
debt_equity_ratio("Previous")

array([0.])

In [16]:
def equity_multiplier_ratio(quarter):
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc(quarter)].values
    te = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc(quarter)].values
    
    result = ta / te
    return result

In [17]:
equity_multiplier_ratio("Previous")

array([5.82578269])

In [18]:
def receivables_turnover_ratio(quarter):
    sales = income_df.iloc[income_df[income_df['Items'] == 'Revenue/sales'].index, income_df.columns.get_loc(quarter)].values
    ar = balance_df.iloc[balance_df[balance_df['Items'] == 'Accounts receivables'].index, balance_df.columns.get_loc(quarter)].values
    
    result = sales / ar
    return result

In [19]:
receivables_turnover_ratio("Current")

array([1.17156185])

In [20]:
#days in sales receivables
days_receivables = 365 / receivables_turnover_ratio("Current")
days_receivables
    

array([311.54992015])

In [21]:
def inventory_turnover_ratio(quarter):
    cogs = income_df.iloc[income_df[income_df['Items'] == 'COGS'].index, income_df.columns.get_loc(quarter)].values
    inv = balance_df.iloc[balance_df[balance_df['Items'] == 'Inventory'].index, balance_df.columns.get_loc(quarter)].values
    
    result = cogs / inv
    return result

In [22]:
inventory_turnover_ratio("Previous")

array([3.69004567])

In [23]:
#days in sales inventory
days_inventory = 365 / inventory_turnover_ratio("Previous")
days_inventory

array([98.91476493])

In [24]:
(365 / inventory_turnover_ratio("Previous"))

array([98.91476493])

In [25]:
def accounts_payable_ratio(quarter):
    cogs = income_df.iloc[income_df[income_df['Items'] == 'COGS'].index, income_df.columns.get_loc(quarter)].values
    ap = balance_df.iloc[balance_df[balance_df['Items'] == 'Accounts payable'].index, balance_df.columns.get_loc(quarter)].values
    
    result = cogs / ap
    return result
    

In [26]:
accounts_payable_ratio("Current")

array([0.85755072])

In [27]:
def ta_turnover_ratio(quarter):
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc(quarter)].values
    sales = income_df.iloc[income_df[income_df['Items'] == 'Revenue/sales'].index, income_df.columns.get_loc(quarter)].values
    
    result = sales / ta
    return result
    

In [28]:
ta_turnover_ratio("Previous")

array([1.68305013])

In [29]:
def profit_margin_ratio(quarter):
    ni = income_df.iloc[income_df[income_df['Items'] == 'Net income'].index, income_df.columns.get_loc(quarter)].values
    sales = income_df.iloc[income_df[income_df['Items'] == 'Revenue/sales'].index, income_df.columns.get_loc(quarter)].values
    
    result = ni / sales
    return result

In [30]:
profit_margin_ratio("Previous")

array([0.02783892])

In [31]:
def roe_ratio(quarter):
    ni = income_df.iloc[income_df[income_df['Items'] == 'Net income'].index, income_df.columns.get_loc(quarter)].values
    te = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc(quarter)].values
    
    result = ni / te
    return result
    

In [32]:
roe_ratio("Previous")

array([0.27296298])

In [33]:
def roa_ratio(quarter):
    ni = income_df.iloc[income_df[income_df['Items'] == 'Net income'].index, income_df.columns.get_loc(quarter)].values
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc(quarter)].values
    
    result = ni / ta
    return result

In [34]:
roa_ratio("Previous")

array([0.0468543])

In [35]:
# du pont
dupont = profit_margin_ratio("Previous") + ta_turnover_ratio("Previous") + equity_multiplier_ratio("Previous")
dupont

array([7.53667174])

In [36]:
def load_ratio():
    return pd.DataFrame(
        {
            "Ratio ": ["Current", "Quick", "Cash", "Total Debt", "Debt-to-Equity","Equity multiplier",
                      "Receivables Turnover", "Days in sales in receivables", "Inventory Turnover", "Days in sales in inventory",
                      "Accounts payable", "Total asset turnover", "Profit margin", "ROE", "ROA", "DU-PONT"],
            "Previous": [current_ratio("Previous"), quick_ratio("Previous"), cash_ratio("Previous"),td_ratio("Previous"),
                        debt_equity_ratio("Previous"), equity_multiplier_ratio("Previous"), receivables_turnover_ratio("Previous"),
                        (365 / receivables_turnover_ratio("Previous")),inventory_turnover_ratio("Previous"),
                        (365 / inventory_turnover_ratio("Previous")), accounts_payable_ratio("Previous"), 
                        ta_turnover_ratio("Previous"), profit_margin_ratio("Previous"), roe_ratio("Previous"),
                        roa_ratio("Previous"), 
                        (profit_margin_ratio("Previous") + ta_turnover_ratio("Previous") + equity_multiplier_ratio("Previous")) ],
            "Current": [current_ratio("Current"), quick_ratio("Current"), cash_ratio("Current"),td_ratio("Current"),
                        debt_equity_ratio("Current"), equity_multiplier_ratio("Current"), receivables_turnover_ratio("Current"),
                        (365 / receivables_turnover_ratio("Current")),inventory_turnover_ratio("Current"),
                        (365 / inventory_turnover_ratio("Current")), accounts_payable_ratio("Current"), 
                        ta_turnover_ratio("Current"), profit_margin_ratio("Current"), roe_ratio("Current"),
                        roa_ratio("Current"), 
                        (profit_margin_ratio("Current") + ta_turnover_ratio("Current") + equity_multiplier_ratio("Current")) ]
        }
    )

In [37]:
df = load_ratio()

In [38]:
df

Ratio                 Previous  \
0                        Current    [1.0899152831344219]   
1                          Quick    [0.5564748185239161]   
2                           Cash   [0.05476738797108348]   
3                     Total Debt                   [0.0]   
4                 Debt-to-Equity                   [0.0]   
5              Equity multiplier     [5.825782686195772]   
6           Receivables Turnover     [4.261405568579339]   
7   Days in sales in receivables     [85.65249050483668]   
8             Inventory Turnover     [3.690045669782163]   
9     Days in sales in inventory     [98.91476492797644]   
10              Accounts payable    [2.0962807298222086]   
11          Total asset turnover    [1.6830501321634361]   
12                 Profit margin  [0.027838922466726868]   
13                           ROE    [0.2729629821630093]   
14                           ROA   [0.04685430213691231]   
15                       DU-PONT     [7.536671740825936]   

                   Current  
0     [1.1083634453936835]  
1      [0.728008234777003]  
2   [0.009629881021686645]  
3                    [0.0]  
4                    [0.0]  
5      [4.894747832225644]  
6     [1.1715618473774574]  
7     [311.54992014894725]  
8     [2.1108090682274607]  
9     [172.91947694089953]  
10    [0.8575507173634671]  
11    [0.6463767760603055]  
12  [0.021573406892521622]  
13   [0.06825505194762974]  
14  [0.013944549195825301]  
15     [5.562698015178471]

In [39]:
def prev_balance_forecast():
    ta_index = balance_df[balance_df['Items']=='Total asset'].index.values
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Previous")].values
    
    cl_index = balance_df[balance_df['Items']=='Total liabilities'].index.values
    tl = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Previous")].values
    
    se_index = balance_df[balance_df['Items']=='Stockholders equity'].index.values
    se = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Previous")].values
    
    for a in range(0, (2 +int(ta_index))):
        ta_perc =  ((balance_df["Previous"][:a] / ta)*100).round(2)
    
    for b in range((int(ta_index)), (2 + int(cl_index))):
        bs = (1 + int(ta_index))
        tl_perc = ((balance_df["Previous"][bs:b] / tl)*100).round(2)
    
    for c in range((int(cl_index)), (2 + int(se_index))):
        ci = (1 + int(cl_index))
        se_perc = ((balance_df["Previous"][ci:c] / se)*100).round(2) 
        
    prev = pd.concat([ta_perc, tl_perc, se_perc])
    balance_df["Previous %"] = prev.tolist()
    
    return balance_df

In [40]:
prev_balance_forecast()

Items  Previous   Current  Previous %
0      Cash and cash equivalents   1325553    201888        4.54
1           Accounts receivables  11539999  14536542       39.50
2                Tax receivables    602990    524077        2.06
3              Other receivables         0         0        0.00
4         Other short-term asset         0         0        0.00
5                      Inventory  12910944   7972010       44.19
6                Prepaid expense        88      2038        0.00
7            Other current asset         0         0        0.00
8                            SDS         0         0        0.00
9           Total current assets  26379576  23236557       90.28
10                           PPE   2834360   3106204        9.70
11              Intangible asset      4810      4810        0.02
12              Biological asset         0         0        0.00
13          Long-term investment         0         0        0.00
14                  Deferred tax         0         0        0.00
15       Other non-current asset         0         0        0.00
16       Total non-current asset   2839171   3111014        9.72
17                   Total asset  29218747  26347571      100.00
18              Accounts payable  22726905  19622619       93.90
19              Salaries payable     75084     57735        0.31
20                   Tax payable    124604     71167        0.51
21     Social securities payable     40812     18756        0.17
22               Short-term debt         0         0        0.00
23              Interest payable         0         0        0.00
24              Dividend payable   1198755   1154371        4.95
25              Unearned revenue         0         0        0.00
26  Other short-term liabilities     37165     40096        0.15
27     Total current liabilities  24203327  20964745      100.00
28                Long-term debt         0         0        0.00
29           Deferred income tax         0         0        0.00
30   Other long-term liabilities         0         0        0.00
31   Total long-term liabilities         0         0        0.00
32             Total liabilities  24203327  20964745      100.00
33                        Equity    377820    377820        7.53
34                  Common stock    377820    377820        7.53
35                Diluted stocks   1402398   1402398       27.96
36             Retained earnings   3235201   3602607       64.51
37           Stockholders equity   5015420   5382825      100.00

In [41]:
def current_balance_forecast():
    ta_index = balance_df[balance_df['Items']=='Total asset'].index.values
    ta = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Current")].values
    
    tl_index = balance_df[balance_df['Items']=='Total liabilities'].index.values
    tl = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Current")].values
    
    se_index = balance_df[balance_df['Items']=='Stockholders equity'].index.values
    se = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Current")].values
    
    for a in range(0, (2 +int(ta_index))):
        ta_perc =  ((balance_df["Current"][:a] / ta)*100).round(2)
    
    for b in range((int(ta_index)), (2 + int(tl_index))):
        bs = (1 + int(ta_index))
        tl_perc = ((balance_df["Current"][bs:b] / tl)*100).round(2)
    
    for c in range((int(tl_index)), (2 + int(se_index))):
        ci = (1 + int(tl_index))
        se_perc = ((balance_df["Current"][ci:c] / se)*100).round(2)
        
    prev = pd.concat([ta_perc, tl_perc, se_perc])
    balance_df["Current %"] = prev.tolist()
    
    return balance_df

In [42]:
current_balance_forecast()

Items  Previous   Current  Previous %  Current %
0      Cash and cash equivalents   1325553    201888        4.54       0.77
1           Accounts receivables  11539999  14536542       39.50      55.17
2                Tax receivables    602990    524077        2.06       1.99
3              Other receivables         0         0        0.00       0.00
4         Other short-term asset         0         0        0.00       0.00
5                      Inventory  12910944   7972010       44.19      30.26
6                Prepaid expense        88      2038        0.00       0.01
7            Other current asset         0         0        0.00       0.00
8                            SDS         0         0        0.00       0.00
9           Total current assets  26379576  23236557       90.28      88.19
10                           PPE   2834360   3106204        9.70      11.79
11              Intangible asset      4810      4810        0.02       0.02
12              Biological asset         0         0        0.00       0.00
13          Long-term investment         0         0        0.00       0.00
14                  Deferred tax         0         0        0.00       0.00
15       Other non-current asset         0         0        0.00       0.00
16       Total non-current asset   2839171   3111014        9.72      11.81
17                   Total asset  29218747  26347571      100.00     100.00
18              Accounts payable  22726905  19622619       93.90      93.60
19              Salaries payable     75084     57735        0.31       0.28
20                   Tax payable    124604     71167        0.51       0.34
21     Social securities payable     40812     18756        0.17       0.09
22               Short-term debt         0         0        0.00       0.00
23              Interest payable         0         0        0.00       0.00
24              Dividend payable   1198755   1154371        4.95       5.51
25              Unearned revenue         0         0        0.00       0.00
26  Other short-term liabilities     37165     40096        0.15       0.19
27     Total current liabilities  24203327  20964745      100.00     100.00
28                Long-term debt         0         0        0.00       0.00
29           Deferred income tax         0         0        0.00       0.00
30   Other long-term liabilities         0         0        0.00       0.00
31   Total long-term liabilities         0         0        0.00       0.00
32             Total liabilities  24203327  20964745      100.00     100.00
33                        Equity    377820    377820        7.53       7.02
34                  Common stock    377820    377820        7.53       7.02
35                Diluted stocks   1402398   1402398       27.96      26.05
36             Retained earnings   3235201   3602607       64.51      66.93
37           Stockholders equity   5015420   5382825      100.00     100.00

In [43]:
balance_df

Items  Previous   Current  Previous %  Current %
0      Cash and cash equivalents   1325553    201888        4.54       0.77
1           Accounts receivables  11539999  14536542       39.50      55.17
2                Tax receivables    602990    524077        2.06       1.99
3              Other receivables         0         0        0.00       0.00
4         Other short-term asset         0         0        0.00       0.00
5                      Inventory  12910944   7972010       44.19      30.26
6                Prepaid expense        88      2038        0.00       0.01
7            Other current asset         0         0        0.00       0.00
8                            SDS         0         0        0.00       0.00
9           Total current assets  26379576  23236557       90.28      88.19
10                           PPE   2834360   3106204        9.70      11.79
11              Intangible asset      4810      4810        0.02       0.02
12              Biological asset         0         0        0.00       0.00
13          Long-term investment         0         0        0.00       0.00
14                  Deferred tax         0         0        0.00       0.00
15       Other non-current asset         0         0        0.00       0.00
16       Total non-current asset   2839171   3111014        9.72      11.81
17                   Total asset  29218747  26347571      100.00     100.00
18              Accounts payable  22726905  19622619       93.90      93.60
19              Salaries payable     75084     57735        0.31       0.28
20                   Tax payable    124604     71167        0.51       0.34
21     Social securities payable     40812     18756        0.17       0.09
22               Short-term debt         0         0        0.00       0.00
23              Interest payable         0         0        0.00       0.00
24              Dividend payable   1198755   1154371        4.95       5.51
25              Unearned revenue         0         0        0.00       0.00
26  Other short-term liabilities     37165     40096        0.15       0.19
27     Total current liabilities  24203327  20964745      100.00     100.00
28                Long-term debt         0         0        0.00       0.00
29           Deferred income tax         0         0        0.00       0.00
30   Other long-term liabilities         0         0        0.00       0.00
31   Total long-term liabilities         0         0        0.00       0.00
32             Total liabilities  24203327  20964745      100.00     100.00
33                        Equity    377820    377820        7.53       7.02
34                  Common stock    377820    377820        7.53       7.02
35                Diluted stocks   1402398   1402398       27.96      26.05
36             Retained earnings   3235201   3602607       64.51      66.93
37           Stockholders equity   5015420   5382825      100.00     100.00

In [44]:
def ave_forecast():
    balance_df['Average %'] = (balance_df["Previous %"] +  balance_df["Current %"]) / 2
    
    return balance_df


In [45]:
ave_forecast()

Items  Previous   Current  Previous %  Current %  \
0      Cash and cash equivalents   1325553    201888        4.54       0.77   
1           Accounts receivables  11539999  14536542       39.50      55.17   
2                Tax receivables    602990    524077        2.06       1.99   
3              Other receivables         0         0        0.00       0.00   
4         Other short-term asset         0         0        0.00       0.00   
5                      Inventory  12910944   7972010       44.19      30.26   
6                Prepaid expense        88      2038        0.00       0.01   
7            Other current asset         0         0        0.00       0.00   
8                            SDS         0         0        0.00       0.00   
9           Total current assets  26379576  23236557       90.28      88.19   
10                           PPE   2834360   3106204        9.70      11.79   
11              Intangible asset      4810      4810        0.02       0.02   
12              Biological asset         0         0        0.00       0.00   
13          Long-term investment         0         0        0.00       0.00   
14                  Deferred tax         0         0        0.00       0.00   
15       Other non-current asset         0         0        0.00       0.00   
16       Total non-current asset   2839171   3111014        9.72      11.81   
17                   Total asset  29218747  26347571      100.00     100.00   
18              Accounts payable  22726905  19622619       93.90      93.60   
19              Salaries payable     75084     57735        0.31       0.28   
20                   Tax payable    124604     71167        0.51       0.34   
21     Social securities payable     40812     18756        0.17       0.09   
22               Short-term debt         0         0        0.00       0.00   
23              Interest payable         0         0        0.00       0.00   
24              Dividend payable   1198755   1154371        4.95       5.51   
25              Unearned revenue         0         0        0.00       0.00   
26  Other short-term liabilities     37165     40096        0.15       0.19   
27     Total current liabilities  24203327  20964745      100.00     100.00   
28                Long-term debt         0         0        0.00       0.00   
29           Deferred income tax         0         0        0.00       0.00   
30   Other long-term liabilities         0         0        0.00       0.00   
31   Total long-term liabilities         0         0        0.00       0.00   
32             Total liabilities  24203327  20964745      100.00     100.00   
33                        Equity    377820    377820        7.53       7.02   
34                  Common stock    377820    377820        7.53       7.02   
35                Diluted stocks   1402398   1402398       27.96      26.05   
36             Retained earnings   3235201   3602607       64.51      66.93   
37           Stockholders equity   5015420   5382825      100.00     100.00   

    Average %  
0       2.655  
1      47.335  
2       2.025  
3       0.000  
4       0.000  
5      37.225  
6       0.005  
7       0.000  
8       0.000  
9      89.235  
10     10.745  
11      0.020  
12      0.000  
13      0.000  
14      0.000  
15      0.000  
16     10.765  
17    100.000  
18     93.750  
19      0.295  
20      0.425  
21      0.130  
22      0.000  
23      0.000  
24      5.230  
25      0.000  
26      0.170  
27    100.000  
28      0.000  
29      0.000  
30      0.000  
31      0.000  
32    100.000  
33      7.275  
34      7.275  
35     27.005  
36     65.720  
37    100.000

In [52]:
balance_df

Items  Previous   Current  Previous %  Current %  \
0      Cash and cash equivalents   1325553    201888        4.54       0.77   
1           Accounts receivables  11539999  14536542       39.50      55.17   
2                Tax receivables    602990    524077        2.06       1.99   
3              Other receivables         0         0        0.00       0.00   
4         Other short-term asset         0         0        0.00       0.00   
5                      Inventory  12910944   7972010       44.19      30.26   
6                Prepaid expense        88      2038        0.00       0.01   
7            Other current asset         0         0        0.00       0.00   
8                            SDS         0         0        0.00       0.00   
9           Total current assets  26379576  23236557       90.28      88.19   
10                           PPE   2834360   3106204        9.70      11.79   
11              Intangible asset      4810      4810        0.02       0.02   
12              Biological asset         0         0        0.00       0.00   
13          Long-term investment         0         0        0.00       0.00   
14                  Deferred tax         0         0        0.00       0.00   
15       Other non-current asset         0         0        0.00       0.00   
16       Total non-current asset   2839171   3111014        9.72      11.81   
17                   Total asset  29218747  26347571      100.00     100.00   
18              Accounts payable  22726905  19622619       93.90      93.60   
19              Salaries payable     75084     57735        0.31       0.28   
20                   Tax payable    124604     71167        0.51       0.34   
21     Social securities payable     40812     18756        0.17       0.09   
22               Short-term debt         0         0        0.00       0.00   
23              Interest payable         0         0        0.00       0.00   
24              Dividend payable   1198755   1154371        4.95       5.51   
25              Unearned revenue         0         0        0.00       0.00   
26  Other short-term liabilities     37165     40096        0.15       0.19   
27     Total current liabilities  24203327  20964745      100.00     100.00   
28                Long-term debt         0         0        0.00       0.00   
29           Deferred income tax         0         0        0.00       0.00   
30   Other long-term liabilities         0         0        0.00       0.00   
31   Total long-term liabilities         0         0        0.00       0.00   
32             Total liabilities  24203327  20964745      100.00     100.00   
33                        Equity    377820    377820        7.53       7.02   
34                  Common stock    377820    377820        7.53       7.02   
35                Diluted stocks   1402398   1402398       27.96      26.05   
36             Retained earnings   3235201   3602607       64.51      66.93   
37           Stockholders equity   5015420   5382825      100.00     100.00   

    Average %  
0       2.655  
1      47.335  
2       2.025  
3       0.000  
4       0.000  
5      37.225  
6       0.005  
7       0.000  
8       0.000  
9      89.235  
10     10.745  
11      0.020  
12      0.000  
13      0.000  
14      0.000  
15      0.000  
16     10.765  
17    100.000  
18     93.750  
19      0.295  
20      0.425  
21      0.130  
22      0.000  
23      0.000  
24      5.230  
25      0.000  
26      0.170  
27    100.000  
28      0.000  
29      0.000  
30      0.000  
31      0.000  
32    100.000  
33      7.275  
34      7.275  
35     27.005  
36     65.720  
37    100.000

In [53]:
# forecast

In [47]:
ta_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Previous")].values
ta_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Current")].values


In [55]:
ta_forecast1 = (ta_prev + ta_cur) / 2


In [50]:
tl_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Previous")].values
se_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Previous")].values


In [51]:
tl_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Current")].values
se_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Current")].values


In [61]:
ta_to_tl = ((ta_prev / tl_prev) + (ta_cur / tl_cur)) / 2

In [62]:
tl_forecast1 = ta_forecast1 * ta_to_tl

In [63]:
ta_to_se = ((ta_prev / se_prev) + (ta_cur / se_cur)) / 2

In [64]:
se_forecast1 = ta_forecast1 * ta_to_se

In [65]:
ta_index = balance_df[balance_df['Items']=='Total asset'].index.values
tl_index = balance_df[balance_df['Items']=='Total liabilities'].index.values
se_index = balance_df[balance_df['Items']=='Stockholders equity'].index.values

In [ ]:
def balance_forecast_year1():
    ta_index = balance_df[balance_df['Items']=='Total asset'].index.values    
    tl_index = balance_df[balance_df['Items']=='Total liabilities'].index.values    
    se_index = balance_df[balance_df['Items']=='Stockholders equity'].index.values
    
    ta_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Previous")].values
    ta_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Total asset'].index, balance_df.columns.get_loc("Current")].values
    
    tl_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Previous")].values
    tl_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Total liabilities'].index, balance_df.columns.get_loc("Current")].values

    se_prev = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Previous")].values
    se_cur = balance_df.iloc[balance_df[balance_df['Items'] == 'Stockholders equity'].index, balance_df.columns.get_loc("Current")].values
    
    ta_to_tl = ((ta_prev / tl_prev) + (ta_cur / tl_cur)) / 2
    tl_forecast1 = ta_forecast1 * ta_to_tl
    ta_to_se = ((ta_prev / se_prev) + (ta_cur / se_cur)) / 2
    se_forecast1 = ta_forecast1 * ta_to_se
    
    for a in range(0, (2 +int(ta_index))):
        ta_perc =  ((balance_df["Current"][:a] / ta)*100).round(2)
    
    for b in range((int(ta_index)), (2 + int(tl_index))):
        bs = (1 + int(ta_index))
        tl_perc = ((balance_df["Current"][bs:b] / tl)*100).round(2)
    
    for c in range((int(tl_index)), (2 + int(se_index))):
        ci = (1 + int(tl_index))
        se_perc = ((balance_df["Current"][ci:c] / se)*100).round(2)
        
    #prev = pd.concat([ta_perc, tl_perc, se_perc])
    #balance_df["Current %"] = prev.tolist()
    
    #return balance_df

In [ ]:
ta_index = balance_df[balance_df['Items']=='Total asset'].index.values 

In [ ]:
balance_df